version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: java-postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=12345'
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6378:6379"
